# Generated by Django 3.2.13 on 2022-08-09 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20220803_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('gender', models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж'), ('U', 'И'), ('X', 'Н')], max_length=1, verbose_name='Пол')),
                ('tagline', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тэги')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('created_at', 'user'),
            },
        ),
    ]
