# Generated by Django 3.2.13 on 2022-08-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20220802_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('created_at', 'user'), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
